#name: hello-world
#on: push
#jobs:
#  my-job:
#    runs-on: ubuntu-latest
#    steps:
#      - name: my-step
#      - uses: actions/checkout@v3
#      - run: make say-hello

# file: .github/workflows/hello-world.yml
name: hello-world
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v3
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      - run: make say-hello

